baseurl: "/"
languageCode: "zh-cn"
title: "Blog of Trevor"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Subscribe
      url: "index.xml"

params:
  description: "Blog of Trevor."
  footer: "&copy; [Trevor](https://github.com/Allencpf) 2021 -- 2025 | [Github](https://github.com/Allencpf) | [知乎](https://github.com/Allencpf)"

markup:
  goldmark:
    renderer:
      unsafe: true
